### ISSUE TITLE
Not working with library

### ISSUE THREAD

**Issue by lulara95** [DWilliames/google-sheets-sync-figma#3]
**Describe the bug**
When the plugin is used on a component of which the master component is defined in a separate library it doesn't work.
**To Reproduce**

https://user-images.githubusercontent.com/77491883/104727723-1e1d0180-5736-11eb-9e78-13380e3692ec.mov

**Additional context**
Design system

**Comment by rodnem** [comment]
Any news ???

**Comment by DWilliames** [comment]
Thanks for this! Sorry for the delay in looking into it — I'll dig into this one now, I think I have a hunch as to why this may be the case.

**Comment by DWilliames** [comment]
After looking in to this a bit, I can't seem to reproduce it :( 
It works fine for me when I try using a component imported from a Team Library.

I have a hunch for what it may be; which if included in the release. I'll let you know once the next release is available, and then I'll get you to confirm if it's working.

**Comment by lulara95** [comment]
Thanks for looking in to this :)


Op 30 jan. 2021 om 12:29 heeft David Williames <notifications@github.com> het volgende geschreven:

﻿

After looking in to this a bit, I can't seem to reproduce it :(
It works fine for me when I try using a component imported from a Team Library.

I have a hunch for what it may be; which if included in the release. I'll let you know once the next release is available, and then I'll get you to confirm if it's working.

**Comment by DWilliames** [comment]
No worries.
I pushed an update to the plugin; are you able to verify if it works for you now?

**Comment by lulara95** [comment]
Hi,

I'm sorry, it still doesn't seem to work for me.

________________________________
Van: David Williames <notifications@github.com>
Verzonden: zondag 31 januari 2021 0:11
Aan: DWilliames/google-sheets-sync-figma <google-sheets-sync-figma@noreply.github.com>
CC: lulara95 <laralu1@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [DWilliames/google-sheets-sync-figma] Not working with library (#3)


No worries.
I pushed an update to the plugin; are you able to verify if it works for you now?
